{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "bulletin-board.namespace" . }}
  labels:
    {{- include "bulletin-board.labels" . | nindent 4 }}
{{- end }}
