{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.ycAuth.authorizedKey.id }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalSecrets.ycAuth.secretName }}
  namespace: {{ include "bulletin-board.namespace" . }}
  labels:
    {{- include "bulletin-board.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.externalSecrets.ycAuth.key }}: |
    {{ .Values.externalSecrets.ycAuth.authorizedKey | toJson }}
{{- end }}
