kind: Deployment
apiVersion: apps/v1
metadata:
  name: hexlet-project
  namespace: hexlet-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexlet-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hexlet-application
    spec:
      serviceAccountName: my-service-account
      terminationGracePeriodSeconds: 45
      securityContext:
        runAsNonRoot: true          # Запрет запуска от root
        runAsUser: 1000             # Запуск от пользователя 1000
        runAsGroup: 3000            # Группа 3000
        fsGroup: 2000               # Группа для томов
        seccompProfile:             # Обязательно для restricted
          type: RuntimeDefault
      containers:
      - name: project-devops-deploy
        image: cr.yandex/crpd2isbgl7k3puo75s1/project-devops-deploy:latest
        securityContext:  # Container-level
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: STORAGE_S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: app-credentials 
                key: STORAGE_S3_ENDPOINT
          - name: STORAGE_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: STORAGE_S3_BUCKET
          - name: STORAGE_S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: STORAGE_S3_ACCESS_KEY
          - name: STORAGE_S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: STORAGE_S3_SECRET_KEY
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: SPRING_DATASOURCE_PASSWORD
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: hexlet-project-config
                key: SPRING_PROFILES_ACTIVE
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: hexlet-project-config
                key: JAVA_OPTS
          - name: MANAGEMENT_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: hexlet-project-config
                key: MANAGEMENT_SERVER_PORT
          - name: STORAGE_S3_REGION
            valueFrom:
              configMapKeyRef:
                name: hexlet-project-config
                key: STORAGE_S3_REGION
        lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
      
        readinessProbe:
           httpGet:
             path: /actuator/health
             port: 9090
           initialDelaySeconds: 8
           periodSeconds: 8
           failureThreshold: 3
        resources:
            requests:
              memory: '500Mi'
              cpu: 300m
            limits:
              memory: '1000Mi'
              cpu: 500m