apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
  namespace: hexlet-project
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    # Имя должно совпадать с imagePullSecrets в serviceaccount.yml
    name: docker-registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "cr.yandex": {
                "username": "oauth",
                "password": "{{ .docker_oauth_token }}",
                "auth": "{{ printf "oauth:%s" .docker_oauth_token | b64enc }}"
              }
            }
          }
  data:
  - secretKey: docker_oauth_token
    remoteRef:
      key: e6qjhb4n6kh24vi7o8kg
      property: docker_oauth_token