kind: Service
apiVersion: v1
metadata:
  name: hexlet-project
  namespace: hexlet-project
spec:
  selector:
    app: hexlet-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP